### ISSUE TITLE
Any known issues using this with Python 2.7?

### ISSUE THREAD

**Issue by DarylWM** [cid-harvard/pandas-to-postgres#2]
Hello and thank you for sharing this code; it's exactly what I'm looking for.

My code base is currently Python 2.7. Do you happen to know whether there are any issues on that version?

**Comment by makmanalp** [comment]
Hey @DarylWM! Happy to hear you found this useful. We didn't really expect anyone would find this yet (Out of curiosity, how did you find this? Google?). Since we use python 3 internally, currently we have python 3 stuff in the codebase (f-strings, type hints).

I don't think we're interested in specifically testing for and supporting 2.7. That said, my colleague @bleonard33 is working on removing the obvious incompatibility culprits, and if you run into anything else we're happy to accept PRs.

**Comment by DarylWM** [comment]
Thanks @makmanalp - I intend to move my code to Python 3 so this is another incentive.

**Comment by makmanalp** [comment]
@DarylWM happy to hear - just FYI the py2 specific stuff (as far as we can tell) is removed, so feel free to give that a shot too.
